### ISSUE TITLE
`exclude=["X"]` does not work on ListOf()

### ISSUE THREAD

**Issue by dadrian** [zmap/zschema#51]
Example:

```
"certificate_policies": ListOf(CertificatePoliciesData(), category="Certificate Policies", validation_policy="warn", exclude=["bigquery"]),
```

**Comment by justinbastress** [comment]
So the implementation is, `ListOf.exclude_bigquery` returns `self.object_.exclude_bigquery`...so to work with the current code, the following should work:

```
"certificate_policies": ListOf(CertificatePoliciesData(exclude=["bigquery"]), category="Certificate Policies", validation_policy="warn"),
```

That seems wrong, but it also seems intentional and vaguely consistent with the idea of lists just being "repeated" fields. Also, if we change it, it's unclear what `ListOf(String(exclude=["bigquery"]))` would mean...the list is there, but we're never adding any elements?

**Comment by justinbastress** [comment]
...so, my question is, do we want to change zschema, or the schemas themselves?

**Comment by zakird** [comment]
I vote we change zschema. This sounds like a bug and should be able to call
it on the ListOf
